import os
import sqlite3
import traceback
from datetime import datetime, timedelta
from pathlib import Path

from fastapi import FastAPI, File, Request, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse, FileResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from reportbot.pipeline import run_pipeline
from reportbot.database import init_db, get_summary, get_runs
from reportbot.scheduler import start_scheduler

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
INCOMING_DIR = DATA_DIR / "incoming"
REPORTS_DIR = DATA_DIR / "reports"
QUARANTINE_DIR = DATA_DIR / "quarantine"

for folder in (INCOMING_DIR, REPORTS_DIR, QUARANTINE_DIR):
    folder.mkdir(parents=True, exist_ok=True)

init_db()

app = FastAPI(title="ReportBot", version="1.0.0")
app.mount("/static", StaticFiles(directory=str(BASE_DIR / "static")), name="static")
templates = Jinja2Templates(directory=str(BASE_DIR / "templates"))

@app.on_event("startup")
def startup():
    start_scheduler()

@app.get("/", response_class=HTMLResponse)
def dashboard(request: Request):
    summary = get_summary()
    runs = get_runs(8)
    return templates.TemplateResponse(
        "index.html",
        {"request": request, "summary": summary, "runs": runs}
    )

@app.get("/api/summary")
def api_summary():
    return get_summary()

@app.get("/api/runs")
def api_runs():
    return get_runs(20)

@app.post("/upload")
async def upload_csv(file: UploadFile = File(...)):
    if not file.filename or not file.filename.lower().endswith(".csv"):
        return JSONResponse({"ok": False, "message": "Please upload a CSV file."}, status_code=400)

    safe_name = Path(file.filename).name
    target = INCOMING_DIR / safe_name
    content = await file.read()
    target.write_bytes(content)
    return RedirectResponse(url="/?uploaded=1", status_code=303)

@app.post("/run")
def run_now():
    try:
        result = run_pipeline()
        return JSONResponse({"ok": True, "result": result})
    except Exception as exc:
        traceback.print_exc()
        return JSONResponse({"ok": False, "message": str(exc)}, status_code=500)

@app.get("/reports/{filename}")
def download_report(filename: str):
    safe_name = Path(filename).name
    path = REPORTS_DIR / safe_name
    if not path.exists():
        return JSONResponse({"ok": False, "message": "Report not found."}, status_code=404)
    return FileResponse(path, media_type="application/pdf", filename=safe_name)

@app.get("/health")
def health():
    return {"status": "healthy", "service": "ReportBot", "time": datetime.now().isoformat()}

@app.get("/api/analytics")
def analytics():
    # Return latest analytics JSON generated by the pipeline.
    path = DATA_DIR / "latest_metrics.json"
    if not path.exists():
        return {"available": False}
    import json
    return {"available": True, **json.loads(path.read_text())}
